In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
books = pd.read_csv("books.csv")

print("Books Dataset:")
print(books.head())

print("\nColumns:")
print(books.columns.tolist())

Books Dataset:
                      Title            Author              Genre  Height  \
0  Fundamentals of Wavelets  Goswami, Jaideva  signal_processing     228
1                Data Smart     Foreman, John       data_science     235
2  God Created the Integers  Hawking, Stephen        mathematics     197
3         Superfreakonomics   Dubner, Stephen          economics     179
4               Orientalism      Said, Edward            history     197

       Publisher
0          Wiley
1          Wiley
2        Penguin
3  HarperCollins
4        Penguin

Columns:
['Title', 'Author', 'Genre', 'Height', 'Publisher']

In [3]:
ratings = pd.read_csv(
    "ratings.csv",
    sep="|",
    header=None,
    names=["User", "Title", "Rating"]
)

print("Ratings Dataset:")
print(ratings.head())

print("\nColumns:")
print(ratings.columns.tolist())

Ratings Dataset:
   User                       Title  Rating
0   196                Kolya (1996)       3
1   186    L.A. Confidential (1997)       3
2    22         Heavyweights (1994)       1
3   244  Legends of the Fall (1994)       2
4   166         Jackie Brown (1997)       1

Columns:
['User', 'Title', 'Rating']

In [4]:
print("Number of books:", len(books))
print("Number of ratings:", len(ratings))

print("\nBooks:")
display(books.head())

print("\nRatings:")
display(ratings.head())

Number of books: 211
Number of ratings: 9

Books:

,Title,Author,Genre,Height,Publisher
0,Fundamentals of Wavelets,"Goswami, Jaideva",signal_processing,228,Wiley
1,Data Smart,"Foreman, John",data_science,235,Wiley
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
3,Superfreakonomics,"Dubner, Stephen",economics,179,HarperCollins
4,Orientalism,"Said, Edward",history,197,Penguin

Ratings:

   User                       Title  Rating
0   196                Kolya (1996)       3
1   186    L.A. Confidential (1997)       3
2    22         Heavyweights (1994)       1
3   244  Legends of the Fall (1994)       2
4   166         Jackie Brown (1997)       1

In [5]:
book_matrix = ratings.pivot_table(
    index="Title",
    columns="User",
    values="Rating"
)

book_matrix = book_matrix.fillna(0)

print("User-Book Matrix:")
display(book_matrix.head())

User-Book Matrix:

User,22,115,166,186,196,244,253,298,305
Title,,,,,,,,,
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963),0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
Grease (1978),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
Heavyweights (1994),1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Hunt for Red October, The (1990)",0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Jackie Brown (1997),0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
similarity = cosine_similarity(book_matrix)

print("Cosine similarity calculated successfully!")
print("Matrix shape:", similarity.shape)

Cosine similarity calculated successfully!
Matrix shape: (9, 9)

In [8]:
def recommend_books(book_name, n=5):
    
    if book_name not in book_matrix.index:
        print("Book not found in ratings dataset.")
        return
    
    book_index = book_matrix.index.get_loc(book_name)
    
    scores = list(enumerate(similarity[book_index]))
    
    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )
    
    print("\nRecommended Books:")
    
    count = 0
    
    for index, score in scores[1:]:
        print(book_matrix.index[index])
        
        count += 1
        
        if count == n:
            break

In [9]:
print("Sample book names:\n")

for book in book_matrix.index[:20]:
    print(book)

Sample book names:

Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)
Grease (1978)
Heavyweights (1994)
Hunt for Red October, The (1990)
Jackie Brown (1997)
Jungle Book, The (1994)
Kolya (1996)
L.A. Confidential (1997)
Legends of the Fall (1994)

In [10]:
recommend_books("Kolya (1996)", 5)

Recommended Books:
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)
Grease (1978)
Heavyweights (1994)
Hunt for Red October, The (1990)
Jackie Brown (1997)